base_model: tiiuae/falcon-7b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true
tokenizer_use_fast: true
tokenizer_legacy: true
gptq: false
load_in_8bit: false
load_in_4bit: true
bf16: auto
tf32: true
bfloat16: true
float16: true
lora_on_cpu: true
datasets:
- path: sgsgs
  type: shshs
  train_on_split: train
shuffle_merged_datasets: true
val_set_size: 0.05
sequence_len: 2048
pad_to_sequence_len: true
sample_packing: true
adapter: qlora
lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
output_dir: ./outputs/qlora-out
gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 4
warmup_steps: 10
learning_rate: 0.0002
logging_steps: 1
evals_per_epoch: 4
saves_per_epoch: 1
eval_max_new_tokens: 128
train_on_inputs: false
group_by_length: false
gradient_checkpointing: true
early_stopping_patience: 3
lr_scheduler: cosine
optimizer: paged_adamw_32bit
weight_decay: 1.0e-06
xformers_attention: true
auto_resume_from_checkpoints: true
special_tokens:
  pad_token: <|endoftext|>
  bos_token: <|endoftext|>
  eos_token: <|endoftext|>
strict: false
