base_model: NousResearch/Llama-2-7b-hf
base_model_config: NousResearch/Llama-2-7b-hf
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
tokenizer_use_fast: true
tokenizer_legacy: true
gptq: true
load_in_8bit: false
load_in_4bit: false
bf16: false
fp16: false
tf32: false
bfloat16: true
float16: true
gpu_memory_limit: 20GiB
lora_on_cpu: true
datasets:
- path: sggs/sgsg
  type: alpaca
  train_on_split: train
shuffle_merged_datasets: true
chat_template: chatml
default_system_message: You are a helpful assistant. Please give a long and detailed
  answer.
val_set_size: 0.05
sequence_len: 4096
pad_to_sequence_len: true
sample_packing: true
sample_packing_group_size: 100000
sample_packing_bin_size: 200
adapter: lora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
output_dir: ./outputs/lora-out
gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 10
warmup_steps: 10
learning_rate: 0.0002
logging_steps: 1
evals_per_epoch: 4
saves_per_epoch: 1
eval_max_new_tokens: 128
train_on_inputs: false
group_by_length: false
gradient_checkpointing: true
lr_scheduler: cosine
optimizer: paged_adamw_32bit
weight_decay: 0.0
flash_attention: true
special_tokens:
  bos_token: <s>
  eos_token: </s>
  unk_token: <unk>
strict: false
